### ISSUE TITLE
16bit TIFFs are munged in PIL converstion

### ISSUE THREAD

**Issue by zimeon** [zimeon/iiif#23]
Reported by @jgreidy. Image http://stor.artstor.org/stor/41f7f2fd-4df0-4d02-a056-ac0f584be3f7 is not handled well. "It looks like only the blackest black pixels came through."

**Comment by zimeon** [comment]
```
(py3)simeon@RottenApple iiif>file 41f7f2fd-4df0-4d02-a056-ac0f584be3f7 
41f7f2fd-4df0-4d02-a056-ac0f584be3f7: TIFF image data, big-endian
(py3)simeon@RottenApple iiif>python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> i = Image.open("41f7f2fd-4df0-4d02-a056-ac0f584be3f7")
>>> i.mode
'I;16B'
```

see: http://stackoverflow.com/questions/7247371/python-and-16-bit-tiff

**Comment by jgreidy** [comment]
Hi,
I re-tested this image with the new (1.0.1) version of the static iiif
code.
https://s3.amazonaws.com/sharedshelftosolr.library.cornell.edu/public/test/
100/image/info.json
Source image:
http://stor.artstor.org/stor/41f7f2fd-4df0-4d02-a056-ac0f584be3f7


The code produced an image (old code did not), but it's munged (blackest
of black pixels).
(tile size is now --tilesize 384)

-JGReidy
